name: 04 -Using Actions
on: push
jobs:
   bulid:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: printing Folder
          run: ls -la
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
             node-version: '20.x'
        - name: Install Dependencies
          run: npm ci
          working-directory: 04-using-actions\react-app

