name: 04 -Using Actions
on: push
jobs:
   bulid:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: printing Folders
          run: ls
